version: '3.8'

services:
  nginx:
    build: .
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: owner@domain.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
      - nginx:/var/log/nginx

volumes:
  letsencrypt:
  nginx:
