# Run a security audit and report the status to slack.
# Credits nrwl.io.
# https://github.com/nrwl/nx/blob/master/.github/workflows/npm-audit.yml

name: NPM Audit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Run a security audit
        run: |
          cd project
          npx audit-ci --critical --report-type summary

      - name: Report Status
        if: ${{ always() && github.repository_owner == 'trekkilabs' }}
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          message_format: '{emoji} *{workflow}* {status_message} on <{commit_url}|{commit_sha}>'
          notification_title: '{workflow} has {status_message}'
          footer: 'From <{repo_url}|{repo}>'
          mention_users: 'U012ACMUZHS'
          mention_users_when: 'failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
